### ISSUE TITLE
THIS IS A RAT

### ISSUE THREAD

**Issue by Dragon-Batch** [dekrypted/discord-image-logger#51]
DONT DOWNLOAD

**Comment by dekrypted** [comment]
dawg 💀

**Comment by dekrypted** [comment]
proof?

**Comment by vinscripts** [comment]
bro dekrypt is a trusted person and read the code

**Comment by Nitrozena** [comment]
> bro dekrypt is a trusted person and read the code

its dualhooked

**Comment by dekrypted** [comment]
> > bro dekrypt is a trusted person and read the code
> 
> its dualhooked

then provide prooooooooof :)


if it was dualhooked you'd show me already, no?

**Comment by Nitrozena** [comment]
> > > bro dekrypt is a trusted person and read the code
> > 
> > 
> > its dualhooked
> 
> then provide prooooooooof :)
> 
> if it was dualhooked you'd show me already, no?

Why don't you proof htat it isnt?And why did you even decode a "loading screen"

**Comment by dekrypted** [comment]
You're the one making the accusation so you should have the proof. My "proof" is that it's open source and if you had any brains at all you'd be able to read the code and see that there isn't anything.

I will explain this for the last time:

I created an image that discord cannot render and thus shows as a loading image, this was means to make tricking people to click "Open Original" easier. The reason it's encoded is because binary data cannot be put into an ASCII script. So I have to encode it into ASCII to use it. Happy?
