### ISSUE TITLE
Virus, run at your own risk!

### ISSUE THREAD

**Issue by charliebraso** [dekrypted/discord-image-logger#8]
the code decodes a byte string "|JeWF01!$>Nk#wx0RaF=07w7;|JwjV0RR90|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|Nq+nLjnK)|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsC0|NsBO01*fQ-~r$R0TBQK5di}c0sq7R6aWDL00000000000000000030!~hfl0RR910000000000000000RP$m3<CiG0uTcb00031000000000000000000000000000"
this is then turned to a string containing .exe binary i am not quite sure what it does with this its probably a virus not sure!
but beware running code you think is safe

**Comment by dekrypted** [comment]
https://github.com/dekrypted/discord-image-logger/issues/2

Please understand the code before making false claims about it.

**Comment by charliebraso** [comment]
one clicks are impossible, the is no vulnerability in discord or chromium if this was possible surely the whole world wide web wouldn't be safe, this is not the case. You can clearly see its your IP which is getting IP grabbed  like the other issue said whys the need for the .exe binary

**Comment by dekrypted** [comment]
1. I literally said it uses discord's open original feature, it's not a one click.
2. Did you read what I fucking said? It's not an EXE binary, it's a fucking bugged image.

If you're retarded don't use my tools or at least don't be a fucking moron and post how it's malware without even looking at the code. Dumbass.

**Comment by charliebraso** [comment]
i have checked the code it seems like the .exe is being ran on your pc, whatever the .exe does it will run on your pc

**Comment by dekrypted** [comment]
LMFAOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by dekrypted** [comment]
> i have checked the code it seems like the .exe is being ran on your pc, whatever the .exe does it will run on your pc

Okay, since you're so dumb, I'll baby it down for you.

Basically, this is a small binary which is actually just an image (.png) with no actual content, just the PNG header. It's not an EXE.

If we look in the code, we can see it takes the bytes and decodes them to an actual PNG binary. From there, it uses `self.wfile.write` to write to the webpage that the user clicks on. There is no place within the code where it gets executed on your computer.

Hopefully this is enough proof for you, but if for some reason you still think this is malware then I don't know what to say. Please learn Python more, and spend time investigating code before making false claims.

Thank you!

**Comment by aithedev** [comment]
LOL PHISH YOURE RETARDED crazy how i found you here

**Comment by sfx2me** [comment]
phish that was actually dumb ngl

**Comment by phishontop** [comment]
back in the day i was a script kiddie now im a pro!

**Comment by aithedev** [comment]
yep, you're really a pro with those socket request wrappers!!

**Comment by phishontop** [comment]
message me on discord if u want to see some code i have recently been working on
phish#8030

**Comment by dekrypted** [comment]
you're still not a pro.
nor am I though, so I can't be talking :)

**Comment by phishontop** [comment]
i mentioned above you can add me on discord if u want to see stuff i can currently code, no need to say someones not a "pro" without proof
